- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
- name: ensure nginx is running
  service:
    name: nginx
    state: started
- name: copy nginx conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx