image: admindptinfo/dc:full


variables:
  VAULT_ADDR: https://vault-dc.info.univ-lyon1.fr
  OS_AUTH_URL: https://cloud-info.univ-lyon1.fr:5000/v3
  OS_AUTH_TYPE: v3applicationcredential
  OS_APPLICATION_CREDENTIAL_ID: c4bdb8446adc4ab69cc3fd24612715e3
  ASBD_GROUP: asbd-kevily
  SECRET_FIELD: unsecrectbienbidon

syntax:
  stage: test
  script:
    - ansible-galaxy install -r requirements.yaml
    - ansible-playbook --syntax-check $CI_COMMIT_REF_NAME.yaml
deploy:
  stage: deploy
  script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=gitlab-ci jwt=$CI_JOB_JWT)"
    - export NO_PROXY="$NO_PROXY,cloud-info.univ-lyon1.fr"
    - export no_proxy="$no_proxy,cloud-info.univ-lyon1.fr"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - PRIVATE_KEY=$(vault kv get -field=key kv/$ASBD_GROUP/$CI_PROJECT_NAME)
    - export OS_APPLICATION_CREDENTIAL_SECRET=$(vault kv get -field=$SECRET_FIELD kv/$ASBD_GROUP/$CI_PROJECT_NAME)
    - echo "$PRIVATE_KEY"| ssh-add -
    - ansible-galaxy install -r requirements.yaml
    - ansible-playbook -i openstack.yaml $CI_COMMIT_REF_NAME.yaml
