- name: Play Front
  hosts: lyon
  become: yes
  remote_user: ubuntu
  roles:
    - nginx
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
    - name: copy nginx conf
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf

